---
- name: make conf dir
  become: yes
  become_user: root
  file:
    path: '{{k8s_conf_dir}}'
    owner: '{{k8s_user}}'
    group: '{{k8s_group}}'
    state: directory
    mode: '0755'

- name: write kubeconfig...
  become: yes
  become_user: '{{k8s_user}}'
  with_items:
    - kubeconfig
  template:
    src: environ/{{item}}.j2
    dest: '{{k8s_home_dir}}/{{item}}'
    mode: 0600

- name: configurating components...
  become: yes
  become_user: root
  with_items:
    - config
    - kube-apiserver-known-tokens.csv
    - '{{k8s_components}}'
  template:
    src: environ/{{item}}.j2
    dest: '{{k8s_conf_dir}}/{{item}}'
    owner: '{{k8s_user}}'
    group: '{{k8s_group}}'
    mode: '0644'
