---
- name: make conf dir
  become: yes
  become_user: root
  file: >-
    path={{k8s_conf_dir}}
    owner={{k8s_user}}
    group={{k8s_group}}
    state=directory
    mode=0755

- name: write helper scripts...
  become: yes
  become_user: root
  with_items:
    - kubeconfig.sh
  template: >-
    src=bin/{{item}}.j2
    dest={{k8s_install_dir}}/{{item}}
    mode=0755
    
- name: write kubeconfig...
  become: yes
  become_user: '{{k8s_user}}'
  command: '{{k8s_install_dir}}/kubeconfig.sh {{k8s_home_dir}}/kubeconfig'
  environment:
    K8S_APISERVER_TOKEN: '{{k8s_apiserver_token}}'
  args:
    creates: '{{k8s_home_dir}}/kubeconfig'

- name: configurating components...
  become: yes
  become_user: root
  with_items:
    - config
    - kube-apiserver-known-tokens.csv
    - '{{k8s_components}}'
  template: >-
    src=environ/{{item}}.j2
    dest={{k8s_conf_dir}}/{{item}}
    owner={{k8s_user}}
    group={{k8s_group}}
    mode=0644

