---
- name: create k8s group
  become: yes
  become_user: root
  group: name={{k8s_group}} state=present
  
- name: create k8s user
  become: yes
  become_user: root
  user: >-
    name={{k8s_user}}
    group={{k8s_group}}
    groups=docker
    home={{k8s_home_dir}}
    state=present

- include: conf.yml
- include: pki.yml
  when: '{{k8s_secured|default(True)}}'
- include: '{{k8s_init|default("systemd")}}.yml'
