---
- name: create k8s group
  become: yes
  become_user: root
  group:
    name: '{{k8s_group}}'
    state: present
  
- name: create k8s user
  become: yes
  become_user: root
  user:
    name: '{{k8s_user}}'
    group: '{{k8s_group}}'
    append: yes
    groups: '{{k8s_addl_groups}}'
    home: '{{k8s_home_dir}}'
    state: present

- name: get k8s users userid
  become: yes
  become_user: root
  getent:
    database: passwd
    key: '{{k8s_user}}'

- name: store k8s userid into var
  become: yes
  become_user: root
  debug:
    msg: "{{getent_passwd[k8s_user][1]}}"
  register: k8s_user_id

- name: change k8s dir ownership to k8s user
  become: yes
  become_user: root
  file:
    path: '{{k8s_home_dir}}'
    owner: '{{k8s_user}}'
    group: '{{k8s_group}}'
    state: directory
    mode: '0755'

- include_tasks: pki.yml
  when: '{{k8s_secured}}'
  
- include_tasks: conf.yml

- include_tasks: '{{k8s_init|default("systemd")}}.yml'

- include_tasks: addons.yml
  when: '{{k8s_install_addons | default(True)}}'
