---
- name: create k8s group
  become: yes
  become_user: root
  group: name={{k8s_group}} gid={{k8s_group_id}} state=present
  
- name: create k8s user
  become: yes
  become_user: root
  user: >-
    name={{k8s_user}}
    group={{k8s_group}}
    uid={{k8s_user_id}}
    groups=docker
    home={{k8s_home_dir}}
    state=present

- name: change k8s dir ownership to k8s user
  become: yes
  become_user: root
  file: >-
    path={{k8s_home_dir}}
    owner={{k8s_user}}
    group={{k8s_group}}
    state=directory
    mode=0755 

- include: pki.yml
  when: '{{k8s_secured}}'
  
- include: conf.yml

- include: '{{k8s_init|default("systemd")}}.yml'
