---
- name: installing services...
  become: yes
  become_user: root
  with_items: '{{k8s_components}}'
  template:
    src: services/{{item}}.service.j2
    dest: /etc/systemd/system/{{item}}.service
    mode: '0644'
  notify:
    - systemctl daemon-reload
    - restarting k8s services
